user1:
  profile: user1
  region: "ap-southeast-1"
  localhost: http://localhost:8000
  remotehost: https://user1.xxxx.com
  request: https://sqs.{{region}}.amazonaws.com/{{accountId}}/{{queueId}}
  response: https://sqs.{{region}}.amazonaws.com/{{accountId}}/{{queueId}}
  whitelist:
    - "/v1/test/*"
    - "/v2/test/*"

user2:
  profile: user2
  region: "ap-southeast-1"
  localhost: http://localhost:8000
  remotehost: https://user1.xxxx.com
  request: https://sqs.{{region}}.amazonaws.com/{{accountId}}/{{queueId}}
  response: https://sqs.{{region}}.amazonaws.com/{{accountId}}/{{queueId}}
  whitelist:
    - "/v1/test/*"
    - "/v2/test/*"

user3:
  profile: user3
  region: "ap-southeast-1"
  localhost: http://localhost:8000
  remotehost: https://user1.xxxx.com
  request: https://sqs.{{region}}.amazonaws.com/{{accountId}}/{{queueId}}
  response: https://sqs.{{region}}.amazonaws.com/{{accountId}}/{{queueId}}
  whitelist:
    - "/v1/test/*"
    - "/v2/test/*"

